export {Navbar} from "./navbar"
export {Banner} from "./banner"
export {Statics} from "./statics"
export {Projects} from "./projects"
export {Services} from "./services"
export {Contact} from "./contact"
export {Testimonials} from "./testimonials"
export {Footer} from "./footer"
